name: Test-Triage
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Triage Issue
        uses: machine-learning-apps/kubeflow-triage@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          PROJECT_CARD_ID: 1 #test id
        